grpc:
  port: 8080

# я считаю логично держать в config logger level и message chan size,
# но так как уже существующий интерфейс не подразумевает передачу
# параметров в NewSubPub эти параметры не будут использоваться.
# Но в будущем можно модифицировать NewSubPub и использовать их
logging:
  level: "info"
subpub:
  message_channel_size: 1000
